/// Languages the Daily Quiz can be presented in.
///
/// [english] is always the default — the backend serves English question text
/// and any Nepali variant is layered on top of it (see
/// `QuizQuestion.textFor`).
enum QuizLanguage {
  english('en', 'EN'),
  nepali('np', 'NP');

  const QuizLanguage(this.code, this.shortLabel);

  /// ISO-ish code sent to the API (`?language=en|np`).
  final String code;

  /// Compact label rendered inside the EN | NP toggle.
  final String shortLabel;

  /// Tolerant parser — the backend (and stored preferences) may use `ne`,
  /// `nep`, `nepali` or `np` for Nepali. Anything unknown falls back to
  /// English so a bad value can never blank out the UI.
  static QuizLanguage fromCode(String? code) {
    switch (code?.trim().toLowerCase()) {
      case 'np':
      case 'ne':
      case 'nep':
      case 'nepali':
        return QuizLanguage.nepali;
      default:
        return QuizLanguage.english;
    }
  }
}

class QuizSchedule {
  final String id;
  final String title;
  final DateTime startDateTime;
  final DateTime endDateTime;
  final int durationMinutes;
  final int totalQuestions;
  final bool allowRetry;
  final int maxRetries;
  final String status;
  final Map<String, dynamic>? metadata;

  const QuizSchedule({
    required this.id,
    required this.title,
    required this.startDateTime,
    required this.endDateTime,
    required this.durationMinutes,
    required this.totalQuestions,
    required this.allowRetry,
    required this.maxRetries,
    required this.status,
    this.metadata,
  });

  /// True when the backend marks this schedule as a daily quiz.
  bool get isDaily => metadata?['isDaily'] == true;

  /// True when this schedule is a deployment generated by a quiz series.
  bool get isSeries =>
      _metadataString('seriesId') != null ||
      _metadataString('seriesTemplateId') != null ||
      metadata?['isSeries'] == true;

  /// Owning series template id, when this schedule is a series deployment.
  String? get seriesId =>
      _metadataString('seriesId') ?? _metadataString('seriesTemplateId');

  /// Server-provided daily date (YYYY-MM-DD), exposed as a getter.
  String? get dailyDate {
    final value = metadata?['dailyDate'];
    return value is String ? value : null;
  }

  /// Total time budget for a single attempt, in seconds.
  int get durationSeconds => durationMinutes * 60;

  /// How many attempts the user is allowed in total.
  ///
  /// Daily quizzes are always single-attempt by product rule, regardless of
  /// what `allowRetry` says on the schedule.
  int get attemptsAllowed {
    if (isDaily) return 1;
    if (!allowRetry) return 1;
    return maxRetries < 1 ? 1 : maxRetries;
  }

  /// True when [now] sits inside the schedule window.
  bool isActiveAt(DateTime now) =>
      !now.isAfter(endDateTime) && !now.isBefore(startDateTime);

  /// True when the schedule window has already closed.
  bool isEndedAt(DateTime now) => now.isAfter(endDateTime);

  String? _metadataString(String key) {
    final value = metadata?[key];
    if (value is String && value.isNotEmpty) return value;
    if (value == null) return null;
    return value.toString();
  }
}

class QuizQuestion {
  final String text;
  final List<String> options;
  final int questionIndex;

  /// Nepali variants supplied by the backend, when present. Empty lists mean
  /// "no translation available" and the English text is used instead.
  final String? textNp;
  final List<String> optionsNp;

  const QuizQuestion({
    required this.text,
    required this.options,
    required this.questionIndex,
    this.textNp,
    this.optionsNp = const [],
  });

  /// Question text for the selected language, falling back to English when no
  /// Nepali variant was provided by the backend.
  String textFor(QuizLanguage language) {
    if (language == QuizLanguage.nepali) {
      final translated = textNp?.trim();
      if (translated != null && translated.isNotEmpty) return translated;
    }
    return text;
  }

  /// Options for the selected language. Falls back to [options] when the
  /// translation is missing or has a different length (indices must stay
  /// aligned with the answer key).
  List<String> optionsFor(QuizLanguage language) {
    if (language == QuizLanguage.nepali &&
        optionsNp.length == options.length &&
        optionsNp.isNotEmpty) {
      return optionsNp;
    }
    return options;
  }
}

class ActiveQuiz {
  final String sessionId;
  final int durationSeconds;
  final List<QuizQuestion> questions;

  /// Schedule this session belongs to — used for display and for the
  /// leaderboard/attempt bookkeeping.
  final String? scheduleId;
  final String? title;
  final bool isDaily;
  final bool isSeries;
  final QuizLanguage language;

  const ActiveQuiz({
    required this.sessionId,
    required this.durationSeconds,
    required this.questions,
    this.scheduleId,
    this.title,
    this.isDaily = false,
    this.isSeries = false,
    this.language = QuizLanguage.english,
  });

  /// Total number of questions in the session.
  int get totalQuestions => questions.length;
}

class AnswerResult {
  final bool isCorrect;
  final int correctAnswerIndex;
  final String explanation;
  final int pointsEarned;
  final String? explanationNp;

  const AnswerResult({
    required this.isCorrect,
    required this.correctAnswerIndex,
    required this.explanation,
    required this.pointsEarned,
    this.explanationNp,
  });

  String explanationFor(QuizLanguage language) {
    if (language == QuizLanguage.nepali) {
      final translated = explanationNp?.trim();
      if (translated != null && translated.isNotEmpty) return translated;
    }
    return explanation;
  }
}

class QuizResult {
  final int score;
  final int maxPossibleScore;
  final int percentageScore;
  final bool passed;
  final int totalQuestions;
  final int correctAnswers;
  final int wrongAnswers;

  /// The user's cumulative leaderboard total as reported by the backend right
  /// after completion (when the backend includes it). Used to show the score
  /// that was added to the leaderboard.
  final int? totalPoints;
  final int? rank;

  const QuizResult({
    required this.score,
    required this.maxPossibleScore,
    required this.percentageScore,
    required this.passed,
    required this.totalQuestions,
    required this.correctAnswers,
    required this.wrongAnswers,
    this.totalPoints,
    this.rank,
  });
}

/// A single entry of `GET /quiz-schedule/history`.
///
/// Used to know up-front whether the user already used their one attempt so
/// the UI can lock the Start button instead of relying on a server error.
class QuizAttempt {
  final String scheduleId;
  final String? sessionId;
  final bool isCompleted;
  final int? score;
  final DateTime? completedAt;

  const QuizAttempt({
    required this.scheduleId,
    this.sessionId,
    this.isCompleted = false,
    this.score,
    this.completedAt,
  });
}

/// A reusable multi-day quiz campaign (`GET /quiz-schedule/series`).
///
/// [deployments] holds the individual schedule instances the backend generated
/// for the series, so the Series tab can show upcoming slots as quiz cards.
class QuizSeries {
  final String id;
  final String title;
  final String? description;
  final int durationValue;
  final String durationUnit;
  final String status;
  final List<QuizSchedule> deployments;

  const QuizSeries({
    required this.id,
    required this.title,
    this.description,
    this.durationValue = 0,
    this.durationUnit = 'days',
    this.status = '',
    this.deployments = const [],
  });
}
